# Lambda Functions - Lab

## Introduction

In this lab, you'll get some hands-on practice creating and using lambda functions.

## Objectives

In this lab you will:

* Create lambda functions to use as arguments of other functions   
* Use the `.map()` or `.apply()` method to apply a function to a pandas series or DataFrame

## Lambda Functions

In [132]:
import pandas as pd
df = pd.read_csv('Yelp_Reviews.csv', index_col=0)
df.head(2)

,business_id,cool,date,funny,review_id,stars,text,useful,user_id
1,pomGBqfbxcqPv14c3XH-ZQ,0,2012-11-13,0,dDl8zu1vWPdKGihJrwQbpw,5,I love this place! My fiance And I go here atl...,0,msQe1u7Z_XuqjGoqhB0J5g
2,jtQARsP6P-LbkyjbO1qNGg,1,2014-10-23,1,LZp4UX5zK3e-c5ZGSeo3kA,1,Terrible. Dry corn bread. Rib tips were all fa...,3,msQe1u7Z_XuqjGoqhB0J5g

## Simple arithmetic

Use a lambda function to create a new column called `'stars_squared'` by squaring the stars column.

In [133]:
df['stars_squared'] = df['stars'].apply(lambda x: x**2) 

df.head()

,business_id,cool,date,funny,review_id,stars,text,useful,user_id,stars_squared
1,pomGBqfbxcqPv14c3XH-ZQ,0,2012-11-13,0,dDl8zu1vWPdKGihJrwQbpw,5,I love this place! My fiance And I go here atl...,0,msQe1u7Z_XuqjGoqhB0J5g,25
2,jtQARsP6P-LbkyjbO1qNGg,1,2014-10-23,1,LZp4UX5zK3e-c5ZGSeo3kA,1,Terrible. Dry corn bread. Rib tips were all fa...,3,msQe1u7Z_XuqjGoqhB0J5g,1
4,Ums3gaP2qM3W1XcA5r6SsQ,0,2014-09-05,0,jsDu6QEJHbwP2Blom1PLCA,5,Delicious healthy food. The steak is amazing. ...,0,msQe1u7Z_XuqjGoqhB0J5g,25
5,vgfcTvK81oD4r50NMjU2Ag,0,2011-02-25,0,pfavA0hr3nyqO61oupj-lA,1,This place sucks. The customer service is horr...,2,msQe1u7Z_XuqjGoqhB0J5g,1
10,yFumR3CWzpfvTH2FCthvVw,0,2016-06-15,0,STiFMww2z31siPY7BWNC2g,5,I have been an Emerald Club member for a numbe...,0,TlvV-xJhmh7LCwJYXkV-cg,25

## Dates
Select the month from the date string using a lambda function.

In [134]:
df['month'] = df['date'].map(lambda x: x.split('-')[1])

print(df['month'])

1       11
2       10
4       09
5       02
10      06
        ..
689     06
4874    08
564     06
3458    10
4206    08
Name: month, Length: 2610, dtype: object

## What is the average number of words for a yelp review?
Do this with a single line of code.

In [135]:
df['text'].map(lambda x : len(x.split())).mean()

77.06551724137931

## Create a new column for the number of words in the review

In [136]:
df['Number_of_Words'] = df['text'].map(lambda x : len(x.split()))

df

,business_id,cool,date,funny,review_id,stars,text,useful,user_id,stars_squared,month,Number_of_Words
1,pomGBqfbxcqPv14c3XH-ZQ,0,2012-11-13,0,dDl8zu1vWPdKGihJrwQbpw,5,I love this place! My fiance And I go here atl...,0,msQe1u7Z_XuqjGoqhB0J5g,25,11,58
2,jtQARsP6P-LbkyjbO1qNGg,1,2014-10-23,1,LZp4UX5zK3e-c5ZGSeo3kA,1,Terrible. Dry corn bread. Rib tips were all fa...,3,msQe1u7Z_XuqjGoqhB0J5g,1,10,30
4,Ums3gaP2qM3W1XcA5r6SsQ,0,2014-09-05,0,jsDu6QEJHbwP2Blom1PLCA,5,Delicious healthy food. The steak is amazing. ...,0,msQe1u7Z_XuqjGoqhB0J5g,25,09,30
5,vgfcTvK81oD4r50NMjU2Ag,0,2011-02-25,0,pfavA0hr3nyqO61oupj-lA,1,This place sucks. The customer service is horr...,2,msQe1u7Z_XuqjGoqhB0J5g,1,02,82
10,yFumR3CWzpfvTH2FCthvVw,0,2016-06-15,0,STiFMww2z31siPY7BWNC2g,5,I have been an Emerald Club member for a numbe...,0,TlvV-xJhmh7LCwJYXkV-cg,25,06,32
...,...,...,...,...,...,...,...,...,...,...,...,...
689,BTcY04QFiS1uh-RpkR7rAg,1,2013-06-02,0,6_A58CCY8SHB7r-Wu7-A5g,5,Came here with my 2 year old daughter for our ...,2,q3AiAe-AcpDrNsdZf8nCvQ,25,06,61
4874,t0T_4MM4EUHbCzBTF11FHA,0,2016-08-14,0,KqQwNyfoFiJOw911mrULIg,5,Great little restaurant. Not to many tables an...,0,NJxaA7q9BhqaDrFpfR2Jeg,25,08,43
564,5XYR6doRa5Nj1JMfSDei6A,1,2016-06-14,0,xlGJkxoIBl8XH8wVsPZpnw,5,Always great friendly service and fresh baked ...,0,kBNFdviedCPFWyR-wVaAzw,25,06,79
3458,aLcFhMe6DDJ430zelCpd2A,0,2013-10-02,0,kwiEG_KCpDB6aK5fTSM7iw,2,We were expecting amazing Thai food after all ...,1,PkRFSQgSfca9Tamq7b2LdQ,4,10,185
4206,WdBWhGe4Siqg3IYTc4_K4A,0,2016-08-15,0,O0ttxNGxHKtD8Cnnwc_j1g,1,Sunday at 8p. Not many people here at all. We ...,0,ic9zIsm7zoxUm3Axyegx8g,1,08,42

## Rewrite the following as a lambda function

Create a new column `'Review_Length'` by applying this lambda function to the `'Review_num_words'` column.

In [137]:
# Rewrite the following function as a lambda function
def rewrite_as_lambda(value):
    if len(value) < 50:
        return 'Short'
    elif len(value) < 80:
        return 'Medium'
    else:
        return 'Long'
# Hint: nest your if, else conditionals

df['Review_length'] = None

## Level Up: Dates Advanced
<img src="images/world_map.png" width="600">  

Print the first five rows of the `'date'` column.

In [138]:
# Your code here
df.head(5)['date']

1     2012-11-13
2     2014-10-23
4     2014-09-05
5     2011-02-25
10    2016-06-15
Name: date, dtype: object

Overwrite the `'date'` column by reordering the month and day from `YYYY-MM-DD` to `DD-MM-YYYY`. Try to do this using a lambda function.

In [150]:
sorted(df['date'], key=lambda x: x.split('-')[0])

['2006-02-16',
 '2006-02-16',
 '2007-10-10',
 '2007-10-06',
 '2007-10-06',
 '2007-10-06',
 '2007-08-11',
 '2007-10-06',
 '2007-10-10',
 '2007-10-06',
 '2007-10-02',
 '2007-10-06',
 '2007-10-06',
 '2007-10-06',
 '2007-10-02',
 '2007-10-06',
 '2007-10-02',
 '2008-05-12',
 '2008-09-15',
 '2008-08-26',
 '2008-10-08',
 '2008-09-27',
 '2008-06-03',
 '2008-10-29',
 '2008-09-28',
 '2008-09-27',
 '2008-10-30',
 '2008-09-29',
 '2008-09-27',
 '2008-06-18',
 '2008-10-08',
 '2008-06-24',
 '2008-08-27',
 '2009-06-29',
 '2009-08-06',
 '2009-10-03',
 '2009-08-06',
 '2009-08-06',
 '2009-08-06',
 '2009-06-29',
 '2009-08-06',
 '2009-08-06',
 '2009-08-06',
 '2009-08-06',
 '2009-08-06',
 '2009-08-06',
 '2009-06-29',
 '2009-06-29',
 '2009-08-06',
 '2009-09-24',
 '2009-11-28',
 '2009-11-28',
 '2009-01-27',
 '2009-06-09',
 '2009-09-02',
 '2009-08-18',
 '2009-12-10',
 '2009-06-09',
 '2009-11-28',
 '2009-08-29',
 '2009-08-26',
 '2009-06-01',
 '2009-08-06',
 '2009-08-18',
 '2009-08-06',
 '2009-06-29',
 '2009-08-26',
 '2009-08-06',
 '2009-11-17',
 '2009-08-06',
 '2009-06-08',
 '2009-06-22',
 '2009-09-27',
 '2009-08-18',
 '2009-06-30',
 '2009-05-09',
 '2009-08-06',
 '2009-09-24',
 '2009-11-10',
 '2010-11-17',
 '2010-07-08',
 '2010-04-02',
 '2010-03-15',
 '2010-03-15',
 '2010-02-16',
 '2010-12-17',
 '2010-12-02',
 '2010-01-31',
 '2010-02-05',
 '2010-09-19',
 '2010-12-13',
 '2010-09-19',
 '2010-06-05',
 '2010-08-30',
 '2010-08-23',
 '2010-09-14',
 '2010-10-12',
 '2010-10-14',
 '2010-11-06',
 '2010-06-27',
 '2010-12-02',
 '2010-09-16',
 '2010-11-13',
 '2010-12-15',
 '2010-12-13',
 '2010-02-02',
 '2010-10-14',
 '2010-06-09',
 '2010-05-08',
 '2010-08-30',
 '2010-06-06',
 '2010-11-29',
 '2010-06-14',
 '2010-01-31',
 '2010-03-17',
 '2010-09-11',
 '2010-01-31',
 '2010-01-25',
 '2010-10-05',
 '2010-02-13',
 '2010-10-18',
 '2010-05-06',
 '2010-09-19',
 '2010-04-02',
 '2010-05-27',
 '2010-10-06',
 '2010-09-21',
 '2010-12-07',
 '2010-11-18',
 '2010-05-11',
 '2010-12-08',
 '2010-02-04',
 '2010-09-16',
 '2010-12-09',
 '2010-09-16',
 '2010-07-07',
 '2010-11-23',
 '2010-05-06',
 '2010-10-08',
 '2010-02-01',
 '2010-01-07',
 '2010-12-27',
 '2010-04-21',
 '2010-11-17',
 '2010-01-24',
 '2010-07-13',
 '2010-02-16',
 '2010-07-18',
 '2011-02-25',
 '2011-09-04',
 '2011-03-04',
 '2011-03-04',
 '2011-07-19',
 '2011-07-26',
 '2011-03-04',
 '2011-07-19',
 '2011-03-04',
 '2011-08-20',
 '2011-08-25',
 '2011-08-25',
 '2011-08-25',
 '2011-04-27',
 '2011-11-26',
 '2011-10-13',
 '2011-10-01',
 '2011-10-27',
 '2011-09-03',
 '2011-06-27',
 '2011-06-12',
 '2011-09-05',
 '2011-12-12',
 '2011-06-25',
 '2011-11-28',
 '2011-11-23',
 '2011-12-19',
 '2011-07-23',
 '2011-01-04',
 '2011-09-21',
 '2011-10-06',
 '2011-10-05',
 '2011-09-09',
 '2011-09-09',
 '2011-12-04',
 '2011-12-17',
 '2011-06-04',
 '2011-07-07',
 '2011-11-26',
 '2011-11-26',
 '2011-10-19',
 '2011-06-06',
 '2011-07-18',
 '2011-07-18',
 '2011-07-18',
 '2011-07-18',
 '2011-07-08',
 '2011-05-15',
 '2011-06-10',
 '2011-12-02',
 '2011-08-16',
 '2011-10-18',
 '2011-08-23',
 '2011-08-10',
 '2011-06-28',
 '2011-12-30',
 '2011-01-12',
 '2011-02-14',
 '2011-03-02',
 '2011-10-06',
 '2011-05-15',
 '2011-09-09',
 '2011-02-28',
 '2011-11-22',
 '2011-01-03',
 '2011-04-06',
 '2011-07-26',
 '2011-02-27',
 '2011-01-29',
 '2011-11-26',
 '2011-10-06',
 '2011-05-27',
 '2011-05-03',
 '2011-03-28',
 '2011-02-25',
 '2011-05-17',
 '2011-05-19',
 '2011-02-23',
 '2011-08-02',
 '2011-12-28',
 '2011-12-19',
 '2011-04-05',
 '2011-09-04',
 '2011-12-18',
 '2011-10-12',
 '2011-09-04',
 '2011-05-02',
 '2011-07-13',
 '2011-08-27',
 '2011-06-29',
 '2011-07-26',
 '2011-10-27',
 '2011-08-16',
 '2011-06-28',
 '2011-01-19',
 '2011-02-25',
 '2011-03-17',
 '2011-09-22',
 '2011-01-06',
 '2011-02-25',
 '2011-10-05',
 '2011-06-18',
 '2011-01-04',
 '2011-06-01',
 '2011-05-08',
 '2011-05-02',
 '2011-04-02',
 '2011-06-06',
 '2011-03-13',
 '2011-06-20',
 '2011-12-05',
 '2011-01-31',
 '2011-02-25',
 '2011-11-18',
 '2011-08-12',
 '2011-10-16',
 '2011-09-05',
 '2011-10-14',
 '2011-04-27',
 '2011-05-31',
 '2011-11-23',
 '2011-11-30',
 '2011-12-01',
 '2011-11-22',
 '2011-01-03',
 '2011-05-01',
 '2011-07-09',
 '2011-06-08',
 '2011-07-23',
 '2011-12-02',
 '2011-11-01',
 '2011-08-25',
 '2011-01-12',
 '2011-06-21',
 '2011-01-07',
 '2011-05-18',
 '2011-05-19',
 '2011-12-30',
 '2011-11-07',
 '2011-09-04',
 '2011-04-10',
 '2011-05-25',
 '2011-07-08',
 '2011-07-03',
 '2011-01-04',
 '2011-10-16',
 '2011-03-18',
 '2011-10-10',
 '2011-09-21',
 '2011-04-07',
 '2011-08-25',
 '2011-08-01',
 '2012-11-13',
 '2012-02-12',
 '2012-02-12',
 '2012-02-12',
 '2012-02-12',
 '2012-10-11',
 '2012-06-10',
 '2012-10-17',
 '2012-08-26',
 '2012-02-17',
 '2012-10-09',
 '2012-07-02',
 '2012-12-26',
 '2012-12-26',
 '2012-12-26',
 '2012-12-26',
 '2012-06-13',
 '2012-05-24',
 '2012-07-15',
 '2012-11-23',
 '2012-09-15',
 '2012-07-31',
 '2012-12-29',
 '2012-08-28',
 '2012-06-21',
 '2012-02-09',
 '2012-07-15',
 '2012-09-02',
 '2012-10-02',
 '2012-07-09',
 '2012-01-02',
 '2012-10-17',
 '2012-03-05',
 '2012-06-15',
 '2012-11-11',
 '2012-07-17',
 '2012-04-18',
 '2012-04-06',
 '2012-04-17',
 '2012-12-10',
 '2012-04-09',
 '2012-04-24',
 '2012-04-06',
 '2012-05-01',
 '2012-07-25',
 '2012-12-20',
 '2012-02-02',
 '2012-08-15',
 '2012-07-25',
 '2012-06-21',
 '2012-02-13',
 '2012-01-31',
 '2012-05-22',
 '2012-07-21',
 '2012-12-19',
 '2012-11-07',
 '2012-01-22',
 '2012-07-02',
 '2012-05-26',
 '2012-07-21',
 '2012-12-12',
 '2012-06-18',
 '2012-07-19',
 '2012-07-16',
 '2012-12-03',
 '2012-12-03',
 '2012-12-03',
 '2012-12-26',
 '2012-12-03',
 '2012-06-08',
 '2012-03-31',
 '2012-12-02',
 '2012-01-03',
 '2012-12-06',
 '2012-06-10',
 '2012-08-06',
 '2012-06-14',
 '2012-06-14',
 '2012-06-18',
 '2012-06-14',
 '2012-06-18',
 '2012-07-02',
 '2012-07-10',
 '2012-07-10',
 '2012-03-18',
 '2012-08-14',
 '2012-08-17',
 '2012-02-28',
 '2012-07-09',
 '2012-02-17',
 '2012-10-29',
 '2012-02-09',
 '2012-10-17',
 '2012-04-08',
 '2012-02-02',
 '2012-04-06',
 '2012-11-14',
 '2012-06-15',
 '2012-08-18',
 '2012-12-07',
 '2012-04-08',
 '2012-04-02',
 '2012-06-21',
 '2012-06-21',
 '2012-02-15',
 '2012-01-13',
 '2012-03-16',
 '2012-07-31',
 '2012-01-13',
 '2012-06-24',
 '2012-07-25',
 '2012-04-28',
 '2012-02-08',
 '2012-09-20',
 '2012-04-05',
 '2012-06-02',
 '2012-06-21',
 '2012-03-18',
 '2012-04-05',
 '2012-11-20',
 '2012-07-15',
 '2012-09-05',
 '2012-08-22',
 '2012-10-21',
 '2012-02-20',
 '2012-04-02',
 '2012-03-16',
 '2012-03-18',
 '2012-01-04',
 '2012-12-19',
 '2012-03-07',
 '2012-05-11',
 '2012-08-30',
 '2012-02-08',
 '2012-12-05',
 '2012-09-28',
 '2012-11-08',
 '2012-07-19',
 '2012-08-05',
 '2012-01-02',
 '2012-06-29',
 '2012-08-18',
 '2012-02-12',
 '2012-11-14',
 '2012-04-18',
 '2012-08-13',
 '2012-08-13',
 '2012-02-04',
 '2012-01-31',
 '2012-02-07',
 '2012-02-10',
 '2012-09-12',
 '2012-12-01',
 '2012-01-03',
 '2012-11-13',
 '2012-06-15',
 '2012-05-05',
 '2012-02-24',
 '2012-08-06',
 '2012-12-29',
 '2012-12-02',
 '2012-06-10',
 '2012-08-13',
 '2012-09-20',
 '2012-07-19',
 '2012-12-26',
 '2012-07-05',
 '2012-10-17',
 '2012-11-20',
 '2012-04-18',
 '2012-06-18',
 '2012-08-12',
 '2012-12-26',
 '2012-11-20',
 '2012-03-09',
 '2012-03-09',
 '2012-11-23',
 '2012-06-03',
 '2012-11-09',
 '2012-09-24',
 '2012-08-28',
 '2012-05-30',
 '2012-11-13',
 '2012-03-16',
 '2012-08-11',
 '2012-07-17',
 '2012-07-31',
 '2012-03-18',
 '2012-08-28',
 '2012-06-05',
 '2012-11-20',
 '2012-12-30',
 '2012-02-04',
 '2012-07-15',
 '2012-07-17',
 '2012-08-14',
 '2012-06-14',
 '2012-05-19',
 '2013-10-04',
 '2013-12-23',
 '2013-08-19',
 '2013-08-25',
 '2013-09-13',
 '2013-09-28',
 '2013-08-26',
 '2013-05-13',
 '2013-07-30',
 '2013-07-30',
 '2013-10-08',
 '2013-05-07',
 '2013-01-31',
 '2013-06-02',
 '2013-06-02',
 '2013-03-10',
 '2013-06-02',
 '2013-03-19',
 '2013-07-28',
 '2013-06-02',
 '2013-03-19',
 '2013-06-02',
 '2013-06-02',
 '2013-03-19',
 '2013-06-02',
 '2013-06-02',
 '2013-06-02',
 '2013-06-02',
 '2013-01-31',
 '2013-02-20',
 '2013-03-13',
 '2013-01-20',
 '2013-01-19',
 '2013-01-20',
 '2013-01-20',
 '2013-01-20',
 '2013-01-20',
 '2013-01-20',
 '2013-01-20',
 '2013-01-20',
 '2013-12-04',
 '2013-12-04',
 '2013-12-20',
 '2013-07-27',
 '2013-11-23',
 '2013-08-14',
 '2013-08-14',
 '2013-08-24',
 '2013-10-10',
 '2013-09-16',
 '2013-03-14',
 '2013-04-27',
 '2013-07-07',
 '2013-07-07',
 '2013-07-07',
 '2013-03-25',
 '2013-11-15',
 '2013-05-16',
 '2013-06-11',
 '2013-03-10',
 '2013-03-24',
 '2013-03-10',
 '2013-03-09',
 '2013-03-07',
 '2013-03-10',
 '2013-03-24',
 '2013-03-24',
 '2013-09-27',
 '2013-01-28',
 '2013-01-28',
 '2013-01-28',
 '2013-02-09',
 '2013-07-29',
 '2013-09-18',
 '2013-09-18',
 '2013-09-18',
 '2013-09-23',
 '2013-09-16',
 '2013-09-29',
 '2013-02-13',
 '2013-08-27',
 '2013-07-13',
 '2013-07-23',
 '2013-01-17',
 '2013-07-04',
 '2013-12-08',
 '2013-12-08',
 '2013-05-15',
 '2013-04-01',
 '2013-08-17',
 '2013-02-27',
 '2013-02-27',
 '2013-07-24',
 '2013-07-24',
 '2013-10-14',
 '2013-08-23',
 '2013-01-08',
 '2013-12-18',
 '2013-08-11',
 '2013-06-13',
 '2013-08-28',
 '2013-08-28',
 '2013-03-05',
 '2013-08-08',
 '2013-10-29',
 '2013-07-12',
 '2013-07-12',
 '2013-03-22',
 '2013-09-15',
 '2013-09-01',
 '2013-11-24',
 '2013-10-16',
 '2013-09-07',
 '2013-09-29',
 '2013-12-05',
 '2013-12-08',
 '2013-12-08',
 '2013-12-08',
 '2013-10-01',
 '2013-11-16',
 '2013-09-21',
 '2013-11-21',
 '2013-10-03',
 '2013-09-27',
 '2013-10-21',
 '2013-04-05',
 '2013-04-05',
 '2013-04-05',
 '2013-03-15',
 '2013-09-29',
 '2013-11-10',
 '2013-02-22',
 '2013-02-26',
 '2013-12-23',
 '2013-12-30',
 '2013-04-04',
 '2013-09-11',
 '2013-09-17',
 '2013-12-16',
 '2013-03-31',
 '2013-02-23',
 '2013-02-24',
 '2013-01-03',
 '2013-01-03',
 '2013-02-27',
 '2013-12-30',
 '2013-04-21',
 '2013-01-14',
 '2013-06-13',
 '2013-09-08',
 '2013-03-01',
 '2013-01-25',
 '2013-12-15',
 '2013-05-29',
 '2013-06-26',
 '2013-06-24',
 '2013-06-26',
 '2013-12-04',
 '2013-07-08',
 '2013-01-03',
 '2013-04-29',
 '2013-06-11',
 '2013-03-07',
 '2013-12-27',
 '2013-05-22',
 '2013-03-31',
 '2013-07-24',
 '2013-07-07',
 '2013-10-19',
 '2013-05-07',
 '2013-08-11',
 '2013-02-22',
 '2013-06-02',
 '2013-01-03',
 '2013-09-24',
 '2013-05-16',
 '2013-08-18',
 '2013-09-01',
 '2013-06-02',
 '2013-06-19',
 '2013-02-16',
 '2013-12-04',
 '2013-06-02',
 '2013-03-24',
 '2013-01-15',
 '2013-07-29',
 '2013-04-28',
 '2013-12-08',
 '2013-07-07',
 '2013-05-08',
 '2013-10-29',
 '2013-04-26',
 '2013-02-09',
 '2013-08-20',
 '2013-07-04',
 '2013-01-02',
 '2013-11-25',
 '2013-03-10',
 '2013-03-10',
 '2013-04-05',
 '2013-04-25',
 '2013-01-20',
 '2013-03-19',
 '2013-01-20',
 '2013-03-14',
 '2013-10-06',
 '2013-09-29',
 '2013-09-24',
 '2013-04-24',
 '2013-06-14',
 '2013-12-15',
 '2013-05-16',
 '2013-07-29',
 '2013-10-14',
 '2013-12-08',
 '2013-07-10',
 '2013-12-08',
 '2013-08-08',
 '2013-05-09',
 '2013-07-07',
 '2013-08-25',
 '2013-03-25',
 '2013-09-14',
 '2013-10-03',
 '2013-12-05',
 '2013-01-17',
 '2013-12-08',
 '2013-10-29',
 '2013-07-12',
 '2013-10-04',
 '2013-08-20',
 '2013-04-11',
 '2013-12-23',
 '2013-06-02',
 '2013-08-28',
 '2013-01-20',
 '2013-05-30',
 '2013-12-08',
 '2013-05-29',
 '2013-09-08',
 '2013-04-11',
 '2013-10-30',
 '2013-02-27',
 '2013-01-26',
 '2013-06-02',
 '2013-08-26',
 '2013-11-29',
 '2013-09-21',
 '2013-06-22',
 '2013-03-24',
 '2013-07-19',
 '2013-12-17',
 '2013-01-20',
 '2013-03-26',
 '2013-05-13',
 '2013-11-22',
 '2013-10-08',
 '2013-07-14',
 '2013-06-13',
 '2013-11-07',
 '2013-11-24',
 '2013-05-20',
 '2013-03-27',
 '2013-05-15',
 '2013-10-21',
 '2013-04-27',
 '2013-08-27',
 '2013-01-27',
 '2013-03-18',
 '2013-12-02',
 '2013-12-30',
 '2013-06-02',
 '2013-02-22',
 '2013-09-05',
 '2013-07-25',
 '2013-01-14',
 '2013-11-06',
 '2013-05-09',
 '2013-04-05',
 '2013-04-25',
 '2013-07-23',
 '2013-08-25',
 '2013-03-20',
 '2013-04-05',
 '2013-04-07',
 '2013-02-13',
 '2013-07-12',
 '2013-08-28',
 '2013-03-01',
 '2013-11-03',
 '2013-06-02',
 '2013-10-02',
 '2014-10-23',
 '2014-09-05',
 '2014-08-23',
 '2014-06-03',
 '2014-03-31',
 '2014-06-07',
 '2014-04-14',
 '2014-08-05',
 '2014-10-28',
 '2014-06-20',
 '2014-06-21',
 '2014-02-18',
 '2014-12-27',
 '2014-06-21',
 '2014-06-22',
 '2014-06-21',
 '2014-06-21',
 '2014-02-11',
 '2014-07-01',
 '2014-07-31',
 '2014-07-30',
 '2014-02-01',
 '2014-02-01',
 '2014-01-27',
 '2014-06-21',
 '2014-07-03',
 '2014-08-28',
 '2014-10-26',
 '2014-09-15',
 '2014-04-11',
 '2014-09-20',
 '2014-08-05',
 '2014-11-08',
 '2014-11-13',
 '2014-11-02',
 '2014-02-22',
 '2014-11-21',
 '2014-06-28',
 '2014-06-28',
 '2014-06-19',
 '2014-03-04',
 '2014-04-01',
 '2014-03-02',
 '2014-09-06',
 '2014-07-19',
 '2014-07-20',
 '2014-10-20',
 '2014-03-28',
 '2014-10-08',
 '2014-01-13',
 '2014-01-11',
 '2014-01-15',
 '2014-10-13',
 '2014-04-09',
 '2014-01-24',
 '2014-02-12',
 '2014-02-12',
 '2014-02-12',
 '2014-07-08',
 '2014-07-02',
 '2014-07-02',
 '2014-07-02',
 '2014-07-02',
 '2014-07-02',
 '2014-07-02',
 '2014-07-02',
 '2014-07-02',
 '2014-07-02',
 '2014-07-03',
 '2014-04-08',
 '2014-09-13',
 '2014-07-23',
 '2014-09-25',
 '2014-09-01',
 '2014-04-12',
 '2014-04-13',
 '2014-09-21',
 '2014-12-04',
 '2014-03-13',
 '2014-07-18',
 '2014-09-18',
 '2014-04-26',
 '2014-04-17',
 '2014-04-26',
 '2014-04-22',
 '2014-04-17',
 '2014-04-26',
 '2014-01-08',
 '2014-07-25',
 '2014-09-20',
 '2014-09-04',
 '2014-12-29',
 '2014-09-24',
 '2014-09-29',
 '2014-09-18',
 '2014-09-03',
 '2014-07-07',
 '2014-08-22',
 '2014-07-07',
 '2014-07-07',
 '2014-03-26',
 '2014-01-22',
 '2014-01-22',
 '2014-08-14',
 '2014-09-25',
 '2014-04-01',
 '2014-04-01',
 '2014-12-27',
 '2014-10-31',
 '2014-08-18',
 '2014-10-14',
 '2014-07-03',
 '2014-04-21',
 '2014-07-27',
 '2014-07-16',
 '2014-12-04',
 '2014-06-12',
 '2014-10-09',
 '2014-10-09',
 '2014-02-20',
 '2014-06-30',
 '2014-09-27',
 '2014-09-20',
 '2014-05-19',
 '2014-10-03',
 '2014-02-22',
 '2014-09-28',
 '2014-02-08',
 '2014-05-22',
 '2014-08-19',
 '2014-08-28',
 '2014-08-28',
 '2014-03-31',
 '2014-03-02',
 '2014-09-12',
 '2014-03-29',
 '2014-10-06',
 '2014-10-06',
 '2014-10-06',
 '2014-06-30',
 '2014-05-02',
 '2014-06-10',
 '2014-10-20',
 '2014-08-30',
 '2014-08-25',
 '2014-05-05',
 '2014-03-09',
 '2014-08-11',
 '2014-05-27',
 '2014-05-26',
 '2014-07-15',
 '2014-07-15',
 '2014-07-15',
 '2014-02-20',
 '2014-12-05',
 '2014-07-08',
 '2014-07-30',
 '2014-04-20',
 '2014-10-09',
 '2014-04-17',
 '2014-11-06',
 '2014-11-20',
 '2014-08-30',
 '2014-08-30',
 '2014-05-28',
 '2014-05-18',
 '2014-11-18',
 '2014-11-02',
 '2014-05-15',
 '2014-03-17',
 '2014-08-21',
 '2014-02-20',
 '2014-06-12',
 '2014-08-23',
 '2014-11-22',
 '2014-12-31',
 '2014-04-15',
 '2014-04-15',
 '2014-04-15',
 '2014-04-15',
 '2014-04-15',
 '2014-04-15',
 '2014-04-15',
 '2014-08-06',
 '2014-03-03',
 '2014-11-08',
 '2014-03-10',
 '2014-12-14',
 '2014-08-05',
 '2014-12-24',
 '2014-03-11',
 '2014-04-26',
 '2014-04-15',
 '2014-06-09',
 '2014-11-14',
 '2014-01-20',
 '2014-05-08',
 '2014-06-14',
 '2014-11-16',
 '2014-03-11',
 '2014-12-07',
 '2014-05-23',
 '2014-03-07',
 '2014-10-28',
 '2014-08-28',
 '2014-11-11',
 '2014-11-11',
 '2014-11-12',
 '2014-11-11',
 '2014-11-11',
 ...]

## Summary

Hopefully, you're getting the hang of lambda functions now! It's important not to overuse them - it will often make more sense to define a function so that it's reusable elsewhere. But whenever you need to quickly apply some simple processing to a collection of data you have a new technique that will help you to do just that. It'll also be useful if you're reading someone else's code that happens to use lambdas.